//I2C APB1
//PB8 PB9


include "stm32f4xx.h"
#define slave_add 0x68


int main(void)
{
RCC->APB1ENR   =0x200000;        //Enable clock access to I2C
RCC->AHB1ENR   =2;               //Enable clock access to PORTB

GPIOB->MODER  &=~0xF0000;
GPIOB->MODER   =0xA0000;         //SET PB8 PB9 to alternate mode

GPIOB->AFRH  &=~0xFF;
GPIOB->AFRH   =0x44;             //SET alternate register

GPIOB->OTYPER =0x200;             //SET PB8 PB9 to open drain
GPIOB->PUPDR &=~0xF0000;
GPIOB->PUPDR  =0x50000;           //SET PULL UP TO PB8 PB9


//I2C Congifuration
I2C->CR1     =0x8000;            //RESET THE I2C BUS
I2C->CR1    &=~0x8000;
I2C->CCR     =80;                //SET master clock frquency 10Mhz
I2C->CR2     =0x10;              //SET peripheral clock frequency 10Mhz.
I2C->TRISE   =17;                //max rise time
I2C->CR1     =1;                 //Peripheral Enabled         
}


int i2c_read(char slave_add,char mem_add,char *data)
{
	volatile int temp;
	while(!(I2C->SR2 & 2)){};        //make sure bus is not busy
	I2C->CR1  =0x100;                //Send Start bit to slave 
	
	while(!(I2C->SR1 & 1)){};         //Check Start bit generated by slave_add
	I2C->DR =mem_add<<1;              //Send some data to DR to start transmission 
	
	while(!(I2C->SR1 & 2)){};        //Check received add. matched
	temp=I2C->SR2;
	
	while(!(I2C->SR2 & 80)){};        //Check recieved add with transmitted
	I2C->DR=mem_add;
	
	while(!(I2C->SR2 & 80)){};
	I2C->CR1  =0x100;
	
	while(!(I2C->SR1 & 1)){};         //Check Start bit generated by slave_add
	I2C->DR =mem_add<<1;              //Send some data to DR to start transmission 
	
	while(!(I2C->SR1 & 2)){};
	I2C->CR1 &=~0x400;     
	tmp=I2C->SR1
	I2C->CR1 |=0x200;
	
	while(!(I2C->SR1 &x40)){};
	*data++=I2C->DR;
	
	return 0;	
}
